/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2023-01-10 ( Date ISO 2023-01-10 - Time 16:17:04 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2023-01-10 ( 16:17:04 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.Madison.entity;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import javax.persistence.*;




/**
* Domain class for entity "CityMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(CityMasterId.class)
@Table(name="CITY_MASTER")


public class CityMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="SNO__", nullable=false)
    private BigDecimal sno ;

    @Id
    @Column(name="CITY_ID", nullable=false)
    private BigDecimal cityId ;

    @Id
    @Column(name="COUNTRY_ID", nullable=false)
    private BigDecimal countryId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="CITY_NAME", nullable=false, length=50)
    private String     cityName ;

    @Column(name="RSACODE", length=10)
    private String     rsacode ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;

    @Column(name="STATUS", length=1)
    private String     status ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



