/*
 * Created on 2023-02-13 ( 15:53:47 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.Madison.entity;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;


import java.math.BigDecimal;

/**
 * Composite primary key for entity "FactorRateRequestDetail" ( stored in table "FACTOR_RATE_REQUEST_DETAIL" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class FactorRateRequestDetailId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private String     requestreferenceno ;
    
    private BigDecimal vehicleId ;
    
    private BigDecimal policytype ;
    
    private String     agencyCode ;
    
     
}
