/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2023-02-13 ( Date ISO 2023-02-13 - Time 15:53:47 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2023-02-13 ( 15:53:47 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.Madison.entity;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "FactorRateRequestDetail"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(FactorRateRequestDetailId.class)
@Table(name="FACTOR_RATE_REQUEST_DETAIL")


public class FactorRateRequestDetail implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="REQUESTREFERENCENO", nullable=false, length=30)
    private String     requestreferenceno ;

    @Id
    @Column(name="VEHICLE_ID", nullable=false)
    private BigDecimal vehicleId ;

    @Id
    @Column(name="POLICYTYPE", nullable=false)
    private BigDecimal policytype ;

    @Id
    @Column(name="AGENCY_CODE", nullable=false, length=10)
    private String     agencyCode ;

    //--- ENTITY DATA FIELDS 
    @Column(name="INSURANCECOMPANYCODE", length=20)
    private String     insurancecompanycode ;

    @Column(name="EPOLICYTYPE")
    private BigDecimal epolicytype ;

    @Column(name="POLICYTYPE_DESC_EN", length=250)
    private String     policytypeDescEn ;

    @Column(name="POLICYTYPE_DESC_AR", length=250)
    private String     policytypeDescAr ;

    @Column(name="AMEND_ID")
    private BigDecimal amendId ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="STATUS", length=20)
    private String     status ;

    @Column(name="REFERAL_STATUS", length=20)
    private String     referalStatus ;

    @Column(name="REFERALL_REMARKS", length=4000)
    private String     referallRemarks ;

    @Column(name="SUMINSURED")
    private BigDecimal suminsured ;

    @Column(name="SCHEME_RATE")
    private BigDecimal schemeRate ;

    @Column(name="TPL_BASE_PREMIUM")
    private BigDecimal tplBasePremium ;

    @Column(name="VEHICLEAGE_RATE")
    private BigDecimal vehicleageRate ;

    @Column(name="VEHICLEUSE_YN", length=150)
    private String     vehicleuseYn ;

    @Column(name="PLATETYPE")
    private BigDecimal platetype ;

    @Column(name="VEHCLEDRIVERUSERATE")
    private BigDecimal vehcledriveruserate ;

    @Column(name="DRIVERAGE_RATE")
    private BigDecimal driverageRate ;

    @Column(name="NCD_LOADING")
    private BigDecimal ncdLoading ;

    @Column(name="PADRIVER")
    private BigDecimal padriver ;

    @Column(name="PAPASSENGER")
    private BigDecimal papassenger ;

    @Column(name="DERIVED_BASE_RATE")
    private BigDecimal derivedBaseRate ;

    @Column(name="DERIVED_BASE_PREMIUM")
    private BigDecimal derivedBasePremium ;

    @Column(name="BASE_GID")
    private BigDecimal baseGid ;

    @Column(name="BASE_EGID")
    private BigDecimal baseEgid ;

    @Column(name="BASE_RATE")
    private BigDecimal baseRate ;

    @Column(name="BASE_PREMIUM")
    private BigDecimal basePremium ;

    @Column(name="MIN_PREMIUM")
    private BigDecimal minPremium ;

    @Column(name="MIN_PREMYN", length=5)
    private String     minPremyn ;

    @Column(name="DRIVER_GID")
    private BigDecimal driverGid ;

    @Column(name="DRIVER_EGID")
    private BigDecimal driverEgid ;

    @Column(name="DRIVERAGE_LOAD_PREMIUM")
    private BigDecimal driverageLoadPremium ;

    @Column(name="DRIVERAGE_PREMIUM")
    private BigDecimal driveragePremium ;

    @Column(name="NCD_GID")
    private BigDecimal ncdGid ;

    @Column(name="NCD_EGID")
    private BigDecimal ncdEgid ;

    @Column(name="NCD_RATE")
    private BigDecimal ncdRate ;

    @Column(name="NCD_PREMIUM")
    private BigDecimal ncdPremium ;

    @Column(name="NO_CLAIMS_RATE")
    private BigDecimal noClaimsRate ;

    @Column(name="CLAIM_LOAD_PREMIUM")
    private BigDecimal claimLoadPremium ;

    @Column(name="LOYAL_GID")
    private BigDecimal loyalGid ;

    @Column(name="LOYAL_EGID")
    private BigDecimal loyalEgid ;

    @Column(name="LOYAL_LOAD_RATE")
    private BigDecimal loyalLoadRate ;

    @Column(name="LOYALTY_PREMIUM")
    private BigDecimal loyaltyPremium ;

    @Column(name="PREMIUM_WO_VAT")
    private BigDecimal premiumWoVat ;

    @Column(name="OPCOVER_SELECTED", length=500)
    private String     opcoverSelected ;

    @Column(name="OPCOVER_PREMIUM")
    private BigDecimal opcoverPremium ;

    @Column(name="FINAL_PREMIUM")
    private BigDecimal finalPremium ;

    @Column(name="VAT_PERCENT")
    private BigDecimal vatPercent ;

    @Column(name="VAT_PREMIUM")
    private BigDecimal vatPremium ;

    @Column(name="NET_PREMIUM")
    private BigDecimal netPremium ;

    @Column(name="OTHER_FEE_1")
    private BigDecimal otherFee1 ;

    @Column(name="OTHER_FEE_2")
    private BigDecimal otherFee2 ;

    @Column(name="OTHER_FEE_3")
    private BigDecimal otherFee3 ;

    @Column(name="OTHER_FEE_PERC_1")
    private BigDecimal otherFeePerc1 ;

    @Column(name="OTHER_FEE_PERC_2")
    private BigDecimal otherFeePerc2 ;

    @Column(name="OTHER_FEE_PERC_3")
    private BigDecimal otherFeePerc3 ;

    @Column(name="TPL_PREMIUM")
    private BigDecimal tplPremium ;

    @Column(name="SEATINGCAPACITY")
    private BigDecimal seatingcapacity ;

    @Column(name="REFERAL_CODES", length=250)
    private String     referalCodes ;

    @Column(name="DEDUCTIBLE_RATE")
    private BigDecimal deductibleRate ;

    @Column(name="DEDUCTIBLE_PREMIUM")
    private BigDecimal deductiblePremium ;

    @Column(name="CURRENCY_TYPE", length=50)
    private String     currencyType ;

    @Column(name="EXCHANGE_RATE")
    private BigDecimal exchangeRate ;

    @Column(name="TOTAL_DAYS")
    private BigDecimal totalDays ;

    @Column(name="NO_OF_DAYS")
    private BigDecimal noOfDays ;

    @Column(name="QUARTER_DISCOUNT_PERCENT")
    private BigDecimal quarterDiscountPercent ;

    @Column(name="PER_DAY_PREMIUM")
    private BigDecimal perDayPremium ;

    @Column(name="ELECTRICAL_PREMIUM")
    private BigDecimal electricalPremium ;

    @Column(name="NON_ELECTRICAL_PREMIUM")
    private BigDecimal nonElectricalPremium ;

    @Column(name="MIN_PREMIUM_ADJUSTMENT")
    private BigDecimal minPremiumAdjustment ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



