/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2023-01-10 ( Date ISO 2023-01-10 - Time 16:20:08 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2023-01-10 ( 16:20:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.Madison.entity;


import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;




/**
* Domain class for entity "MotorPolicyCoverData"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(MotorPolicyCoverDataId.class)
@Table(name="MOTOR_POLICY_COVER_DATA")


public class MotorPolicyCoverData implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="APPLICATION_NO", nullable=false)
    private Long applicationNo ;

    @Id
    @Column(name="POLICYTYPE_COVERID", nullable=false)
    private Long policytypeCoverid ;

    @Id
    @Column(name="BRANCH_CODE", nullable=false, length=8)
    private String     branchCode ;

    @Id
    @Column(name="VEHICLE_ID", nullable=false)
    private Long vehicleId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="QUOTE_NO", nullable=false)
    private Long quoteNo ;

    @Column(name="SUM_INSURED")
    private Double sumInsured ;

    @Column(name="RATE")
    private Double rate ;

    @Column(name="PREMIUM")
    private Double premium ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE")
    private Date       effectiveDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EXPIRY_DATE")
    private Date       expiryDate ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;

    @Column(name="AMEND_ID", nullable=false)
    private Long amendId ;

    @Column(name="OPCOVER_DESC", length=1000)
    private String     opcoverDesc ;

    @Column(name="DESCRIPTION", length=1000)
    private String     description ;

    @Column(name="GROUP_DESC", length=1000)
    private String     groupDesc ;

    @Column(name="GROUP_ID")
    private Long groupId ;

    @Column(name="DISPLAY_ORDER")
    private Long displayOrder ;

    @Column(name="USD_PREMIUM")
    private Double usdPremium ;

    @Column(name="USD_SUM_INSURED")
    private Double usdSumInsured ;

    @Column(name="CURRENCY_ID", length=10)
    private String     currencyId ;

    @Column(name="USD_RATE")
    private Long usdRate ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



