/*
 * Created on 2023-01-10 ( 16:19:39 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.Madison.entity;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;


import java.math.BigDecimal;

/**
 * Composite primary key for entity "MotorFinanceBankMaster" ( stored in table "MOTOR_FINANCE_BANK_MASTER" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class MotorFinanceBankMasterId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private BigDecimal bankId ;
    
    private BigDecimal amendId ;
    
    private String     branchCode ;
    
     
}
