/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2023-01-10 ( Date ISO 2023-01-10 - Time 16:19:39 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2023-01-10 ( 16:19:39 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.Madison.entity;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "MotorFinanceBankMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(MotorFinanceBankMasterId.class)
@Table(name="MOTOR_FINANCE_BANK_MASTER")


public class MotorFinanceBankMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="BANK_ID", nullable=false)
    private BigDecimal bankId ;

    @Id
    @Column(name="AMEND_ID", nullable=false)
    private BigDecimal amendId ;

    @Id
    @Column(name="BRANCH_CODE", nullable=false, length=8)
    private String     branchCode ;

    //--- ENTITY DATA FIELDS 
    @Column(name="BANK_CODE", nullable=false, length=10)
    private String     bankCode ;

    @Column(name="BANK_NAME_ENGLISH", length=100)
    private String     bankNameEnglish ;

    @Column(name="BANK_NAME_ARABIC", length=400)
    private String     bankNameArabic ;

    @Column(name="STATUS", nullable=false, length=1)
    private String     status ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE", nullable=false)
    private Date       effectiveDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EXPIRY_DATE")
    private Date       expiryDate ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;

    @Column(name="ADDRESS1", length=500)
    private String     address1 ;

    @Column(name="ADDRESS2", length=500)
    private String     address2 ;

    @Column(name="TELEPHONE", length=100)
    private String     telephone ;

    @Column(name="MOBILE", length=100)
    private String     mobile ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



