/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2023-01-10 ( Date ISO 2023-01-10 - Time 16:19:19 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2023-01-10 ( 16:19:19 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.Madison.entity;


import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;




/**
* Domain class for entity "MotorDataDetail"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(MotorDataDetailId.class)
@Table(name="MOTOR_DATA_DETAIL")


public class MotorDataDetail implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="APPLICATION_NO", nullable=false)
    private Long applicationNo ;

    @Id
    @Column(name="PRODUCT_ID", nullable=false)
    private Long productId ;

    @Id
    @Column(name="VEHICLE_ID", nullable=false)
    private Long vehicleId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="QUOTE_NO")
    private Long quoteNo ;

    @Column(name="CUSTOMER_ID")
    private Long customerId ;

    @Column(name="AMEND_ID", nullable=false)
    private Long amendId ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;

    @Column(name="SCHEME_ID")
    private Long schemeId ;

    @Column(name="MAKE_ID")
    private Long makeId ;

    @Column(name="MODEL_ID")
    private Long modelId ;

    @Column(name="BODY")
    private Long body ;

    @Column(name="MANUFACTURE_YEAR", length=4)
    private String     manufactureYear ;

    @Column(name="MANUFACTURE_MONTH", length=2)
    private String     manufactureMonth ;

    @Column(name="CUBIC_CAPACITY")
    private Long cubicCapacity ;

    @Column(name="SEATING_CAPACITY")
    private Long seatingCapacity ;

    @Column(name="SUMINSURED_VALUE_FOREIGN")
    private Double suminsuredValueForeign ;

    @Column(name="SUMINSURED_VALUE_LOCAL")
    private Double suminsuredValueLocal ;

    @Column(name="CURRENCY_TYPE", length=50)
    private String     currencyType ;

    @Column(name="VEHICLE_TYPE")
    private Long vehicleType ;

    @Column(name="LEASED", length=1)
    private String     leased ;

    @Column(name="NO_OF_CYLINDER")
    private Long noOfCylinder ;

    @Column(name="AGENCY_REPAIR", length=1)
    private String     agencyRepair ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DRIVER_DOB")
    private Date       driverDob ;

    @Column(name="DRIVER_AGE")
    private Long driverAge ;

    @Column(name="DRIVER_UAE_LICENCE")
    private Long driverUaeLicence ;

    @Column(name="DRIVER_OTHER_LICENCE")
    private Long driverOtherLicence ;

    @Column(name="NO_OF_CLAIMS")
    private Long noOfClaims ;

    @Column(name="NO_CLAIM_BONUS")
    private Long noClaimBonus ;

    @Column(name="AREA_COVERAGE")
    private Long areaCoverage ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="INCEPTION_DATE")
    private Date       inceptionDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE")
    private Date       effectiveDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EXPIRY_DATE")
    private Date       expiryDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENDORSEMENT_DATE")
    private Date       endorsementDate ;

    @Column(name="DRIVER_GENDER", length=1)
    private String     driverGender ;

    @Column(name="THIRD_PARTY_LIABILITY")
    private Long thirdPartyLiability ;

    @Column(name="DRIVER_NATIONALITY")
    private Long driverNationality ;

    @Column(name="DRIVER_LICENSE", length=25)
    private String     driverLicense ;

    @Column(name="PERSONAL_ACCIDENT_DRIVER", length=1)
    private String     personalAccidentDriver ;

    @Column(name="PERSONAL_ACCIDENT_PASSENGER", length=1)
    private String     personalAccidentPassenger ;

    @Column(name="REGISTRATION_NO", length=25)
    private String     registrationNo ;

    @Column(name="CHASSIS_NO", length=25)
    private String     chassisNo ;

    @Column(name="ENGINE_NUMBER", length=25)
    private String     engineNumber ;

    @Column(name="PLATE_COLOR")
    private Long plateColor ;

    @Column(name="VEHICLE_COLOR")
    private Long vehicleColor ;

    @Column(name="INSURED_NAME_ARABIC", length=1000)
    private String     insuredNameArabic ;

    @Column(name="INSURED_ADDRESS_ARABIC", length=2000)
    private String     insuredAddressArabic ;

    @Column(name="BANK_NAME")
    private Long bankName ;

    @Column(name="BASE_RATE")
    private Long baseRate ;

    @Column(name="PREMIUM")
    private Double premium ;

    @Column(name="DISCOUNT_PREMIUM")
    private Double discountPremium ;

    @Column(name="AGENCY_REPAIR_PREMIUM")
    private Double agencyRepairPremium ;

    @Column(name="PA_DRIVER_PREMIUM")
    private Double paDriverPremium ;

    @Column(name="PA_PASSENGER_PREMIUM")
    private Double paPassengerPremium ;

    @Column(name="POLICYTYPE")
    private Long policytype ;

    @Column(name="OPTIONAL_COVER", length=50)
    private String     optionalCover ;

    @Column(name="EXCESS")
    private Long excess ;

    @Column(name="BANK_ID")
    private Long bankId ;

    @Column(name="REGISTER_LOCATION", length=100)
    private String     registerLocation ;

    @Column(name="TRAFFIC_ID")
    private Long trafficId ;

    @Column(name="ENDORSEMENT_STATUS", length=1)
    private String     endorsementStatus ;

    @Column(name="PDF_BROKER_STATUS")
    private Long pdfBrokerStatus ;

    @Column(name="CLAIMYN", length=1)
    private String     claimyn ;

    @Column(name="CLAIM_AMOUNT")
    private Long claimAmount ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DRIVER_UAE_LIC_EXP_DT")
    private Date       driverUaeLicExpDt ;

    @Column(name="REGISTRATION_YEAR", length=10)
    private String     registrationYear ;

    @Column(name="REFERRAL_REMARKS", length=500)
    private String     referralRemarks ;

    @Column(name="DEDUCTIBLE_ID")
    private Long deductibleId ;

    @Column(name="MANUFACTURE_LOC")
    private Long manufactureLoc ;

    @Column(name="DRIVER_ID", length=50)
    private String     driverId ;

    @Column(name="ELECTRICAL_SI")
    private Long electricalSi ;

    @Column(name="NONELECTRICAL_SI")
    private Long nonelectricalSi ;

    @Column(name="PREV_POLICYNO", length=100)
    private String     prevPolicyno ;

    @Column(name="INS_COMPANY", length=200)
    private String     insCompany ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PREV_POLICYEXPIRYDATE")
    private Date       prevPolicyexpirydate ;

    @Column(name="VAT")
    private Long vat ;

    @Column(name="NONELECTRICAL_RATE")
    private Long nonelectricalRate ;

    @Column(name="NONELECTRICAL_PREM")
    private Long nonelectricalPrem ;

    @Column(name="ELECTRICAL_RATE")
    private Long electricalRate ;

    @Column(name="ELECTRICAL_PREM")
    private Long electricalPrem ;

    @Column(name="CURRENCY_ID")
    private Long currencyId ;

    @Column(name="POLICY_NO", length=100)
    private String     policyNo ;

    @Column(name="OWNNERDRIVER_YN", length=1)
    private String     ownnerdriverYn ;

    @Column(name="EXCHANGE_RATE")
    private Long exchangeRate ;

    @Column(name="ORIGINAL_POLICY_NO", length=100)
    private String     originalPolicyNo ;

    @Column(name="SUMINSURED_VALUE_LOCAL_ENDT")
    private Double suminsuredValueLocalEndt ;

    @Column(name="ELECTRICAL_SI_ENDT")
    private Long electricalSiEndt ;

    @Column(name="NONELECTRICAL_SI_ENDT")
    private Long nonelectricalSiEndt ;

    @Column(name="CERTIFICATE_NO", length=20)
    private String     certificateNo ;

    @Column(name="ONLINE_DISCOUNT")
    private Long onlineDiscount ;

    @Column(name="DEDUCTIBLE_AMOUNT")
    private Long deductibleAmount ;

    @Column(name="CUSTOMER_TYPE", length=100)
    private String     customerType ;

    @Column(name="MAKE_NAME", length=100)
    private String     makeName ;

    @Column(name="BODY_NAME", length=100)
    private String     bodyName ;

    @Column(name="MODEL_NAME", length=100)
    private String     modelName ;

    @Column(name="VEHICLE_USAGE_NAME", length=100)
    private String     vehUsageName ;

    @Column(name="IS_CLAIMDTL", length=1)
    private String     isclaimdtl ;

}



