/*
 * Java domain class for entity "DocumentMaster" 
 * Created on 2023-02-13 ( Date ISO 2023-02-13 - Time 15:53:30 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2023-02-13 ( 15:53:30 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.Madison.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.Madison.entity.DocumentMaster;
import com.maan.Madison.entity.DocumentMasterId;
/**
 * <h2>DocumentMasterRepository</h2>
 *
 * createdAt : 2023-02-13 - Time 15:53:30
 * <p>
 * Description: "DocumentMaster" Repository
 */
 
 
 
public interface DocumentMasterRepository  extends JpaRepository<DocumentMaster,DocumentMasterId > , JpaSpecificationExecutor<DocumentMaster> {

	List<DocumentMaster> findByProductIdAndStatusIgnoreCase(String productId,String status);

	List<DocumentMaster> findByProductIdAndUserTypeIgnoreCaseAndStatusIgnoreCase(String productId,String userType, String status);

}
