/*
 * Java domain class for entity "FactorRateRequestDetail" 
 * Created on 2023-02-13 ( Date ISO 2023-02-13 - Time 15:53:48 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2023-02-13 ( 15:53:48 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.Madison.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.Madison.entity.FactorRateRequestDetail;
import com.maan.Madison.entity.FactorRateRequestDetailId;
/**
 * <h2>FactorRateRequestDetailRepository</h2>
 *
 * createdAt : 2023-02-13 - Time 15:53:48
 * <p>
 * Description: "FactorRateRequestDetail" Repository
 */
 
 
 
public interface FactorRateRequestDetailRepository  extends JpaRepository<FactorRateRequestDetail,FactorRateRequestDetailId > , JpaSpecificationExecutor<FactorRateRequestDetail> {

}
