/*
 * Java domain class for entity "HomePositionMaster" 
 * Created on 2023-01-10 ( Date ISO 2023-01-10 - Time 16:18:09 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2023-01-10 ( 16:18:09 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.Madison.repository;

import java.util.Map;

import javax.transaction.Transactional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.maan.Madison.entity.HomePositionMaster;
import com.maan.Madison.entity.HomePositionMasterId;
/**
 * <h2>HomePositionMasterRepository</h2>
 *
 * createdAt : 2023-01-10 - Time 16:18:09
 * <p>
 * Description: "HomePositionMaster" Repository
 */
 
 

@Repository
public interface HomePositionMasterRepository  extends JpaRepository<HomePositionMaster,HomePositionMasterId > , JpaSpecificationExecutor<HomePositionMaster> {

	HomePositionMaster findByApplicationNo(Long applicationNo);

	@Query(value = "SELECT SUM( DECODE(CURRENCY_ID,'USD',NVL (A.USD_PREMIUM, '0'), NVL (A.PREMIUM, '0'))) PREMIUM FROM  MOTOR_POLICY_COVER_DATA A WHERE APPLICATION_NO=? AND A.AMEND_ID = (SELECT MAX (AMEND_ID) FROM MOTOR_POLICY_COVER_DATA WHERE QUOTE_NO = A.QUOTE_NO)",nativeQuery=true)
	String getPremium(String applicationNo);
	
	@Query(value = "SELECT EXCESS_SIGN,EXCESS_PREMIUM FROM HOME_POSITION_MASTER WHERE APPLICATION_NO=?1",nativeQuery=true)
	Map<String,Object> getExcessPremium(String appNo);
	
	@Query(value ="SELECT POLICY_FEE_PERCENT FROM BRANCH_MASTER WHERE BRANCH_CODE=?1",nativeQuery=true)
	String getPolicyfeesPercent(String branchCode);	
	
	@Query(value = "SELECT SUM(PREMIUM) FROM MOTOR_DATA_DETAIL WHERE APPLICATION_NO=?1",nativeQuery=true)
	String getPremium(Long applicationNo);

	@Modifying
	@Transactional
	@Query(value="UPDATE MOTOR_DATA_DETAIL SET INCEPTION_DATE=TO_DATE (?1,'DD/MM/YYYY') WHERE APPLICATION_NO=?2",nativeQuery=true)
	int updateMddPolicyDate(String policyStartDate, String applicatioNo);

	@Modifying
	@Transactional
	@Query(value="UPDATE MOTOR_POLICY_DETAILS SET POLICYSTARTDATE=TO_DATE (?1,'DD/MM/YYYY') WHERE APPLICATIONNO=?2",nativeQuery=true)
	int updateMpdPolicyDate(String policyStartDate, String applicatioNo);
	
	@Modifying
	@Transactional
	@Query(value = "UPDATE HOME_POSITION_MASTER SET INCEPTION_DATE=TO_DATE (?1,'DD/MM/YYYY'),POLICY_TERM=TRUNC(EXPIRY_DATE)-TRUNC(TO_DATE(?1,'DD/MM/YYYY')),BROKER_BRANCH=?3,INSTALLMENT_YN=?4 WHERE APPLICATION_NO=?5",nativeQuery=true)
	int updateHpmPolicyDate(String policyStartDate,String brokerBranch,String installmentYn,String applicatioNo);

	@Modifying
	@Transactional
	@Query(value ="UPDATE HOME_POSITION_MASTER SET APPLICATION_ID='1',LOGIN_ID=?1 WHERE APPLICATION_NO=?2",nativeQuery=true)
	int updateHpmReferalBroker(String loginId, String applicationNo);

	


}
