/*
 * Java domain class for entity "ListItemValue" 
 * Created on 2023-01-10 ( Date ISO 2023-01-10 - Time 16:18:27 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2023-01-10 ( 16:18:27 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.Madison.repository;

import java.util.List;
import java.util.Map;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.maan.Madison.entity.ListItemValue;
import com.maan.Madison.entity.ListItemValueId;
/**
 * <h2>ListItemValueRepository</h2>
 *
 * createdAt : 2023-01-10 - Time 16:18:27
 * <p>
 * Description: "ListItemValue" Repository
 */
 
 
@Repository
public interface ListItemValueRepository  extends JpaRepository<ListItemValue,ListItemValueId > , JpaSpecificationExecutor<ListItemValue> {

	List<ListItemValue> findByItemTypeIgnoreCase(String string);

	List<ListItemValue> findByItemTypeIgnoreCaseAndStatus(String itemType, String status);
	
	@Query(value ="SELECT CODE,CODEDESC FROM TABLE(SELECT MOTOR_QUOTATION_DATA(?1,?2,?3,?4,?5,?6,?7,?8) FROM DUAL)",nativeQuery=true)
	List<Map<String,Object>> getDeductible(Object deductible,Object productId,Object branchCode,Object seatingCap,Object vehicleUsage,Object bodyId,Object obj1,Object obj2);

	@Query(value = "SELECT CODE, CODEDESC, CODEVALUE FROM TABLE (SELECT MOTOR_QUOTATION_DATA(?1,?2,?3,?4,'','','','') FROM DUAL)",nativeQuery=true)
	List<Map<String, Object>> getNcbClaims(String type, String productId, String branchCode, String vehicleUsage);

	@Query(value = " SELECT PAYMENTBANK_ID, (SELECT LIV.ITEM_VALUE FROM LIST_ITEM_VALUE LIV WHERE LIV.ITEM_TYPE='PAYMENTTYPE' AND ITEM_CODE=PAYMENT_TYPE) PAYMENT_TYPE, ACCOUNT_HOLDER,AMEND_ID, TO_CHAR(EFFECTIVE_DATE,'DD/MM/YYYY') EFFECTIVE_DATE, DECODE(STATUS,'Y','Active','N','Deactive') STATUS,STATUS STATUS_EDIT,BANK_NAME,REMARKS, ACCOUNT_NUMBER, BRANCH_NAME, BRANCH_CODE, CURRENCY_TYPE, SWIFT_CODE FROM MOTOR_PAYMENT_BANK_MASTER WHERE AMEND_ID = (SELECT MAX(AMEND_ID) FROM MOTOR_PAYMENT_BANK_MASTER MSM WHERE PAYMENTBANK_ID = MSM.PAYMENTBANK_ID)",nativeQuery=true)
	List<Map<String,Object>> getPaymentBank();

}
