/*
 * Java domain class for entity "MailMaster" 
 * Created on 2023-02-13 ( Date ISO 2023-02-13 - Time 15:54:50 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2023-02-13 ( 15:54:50 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.Madison.repository;

import java.util.List;
import java.util.Map;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.maan.Madison.entity.MailMaster;
import com.maan.Madison.entity.MailMasterId;
/**
 * <h2>MailMasterRepository</h2>
 *
 * createdAt : 2023-02-13 - Time 15:54:50
 * <p>
 * Description: "MailMaster" Repository
 */
 
 
 @Repository
public interface MailMasterRepository  extends JpaRepository<MailMaster,MailMasterId > , JpaSpecificationExecutor<MailMaster> {

	MailMaster findByAppId(String appId);

	@Query(value="select * from mail_template_master where remarks='BUY_POLICY_QUOTE_REFERAL' and status='Y'",nativeQuery=true)
	List<Map<String,Object>> getMailTemplateMaster();
}
