/*
 * Java domain class for entity "MotorDataDetail" 
 * Created on 2023-01-10 ( Date ISO 2023-01-10 - Time 16:19:19 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2023-01-10 ( 16:19:19 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.Madison.repository;

import java.util.Date;
import java.util.List;
import java.util.Map;

import javax.transaction.Transactional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.maan.Madison.entity.MotorDataDetail;
import com.maan.Madison.entity.MotorDataDetailId;
/**
 * <h2>MotorDataDetailRepository</h2>
 *
 * createdAt : 2023-01-10 - Time 16:19:19
 * <p>
 * Description: "MotorDataDetail" Repository
 */
 
 
@Repository 
public interface MotorDataDetailRepository  extends JpaRepository<MotorDataDetail,MotorDataDetailId > , JpaSpecificationExecutor<MotorDataDetail> {

	@Query(value ="SELECT APPLICATION_NO.NEXTVAL FROM DUAL",nativeQuery = true)
	Long getApplicatonNo();
	
	@Query(value ="SELECT ONEOFF_QUOTE.NEXTVAL FROM DUAL",nativeQuery = true)
	Long getQuoteNo();
	
	@Query(value = "SELECT NVL (MAX (VEHICLE_ID), 0)+1 FROM MOTOR_DATA_DETAIL WHERE APPLICATION_NO=?1",nativeQuery=true)
	Long getVehicleId(Long applicationNo);

	List<MotorDataDetail> findByApplicationNo(Long applicationNo);

	List<MotorDataDetail> findByApplicationNoAndReferralRemarksIsNotNull(Long applicationNo);

	MotorDataDetail findByApplicationNoAndVehicleId(Long appNo, Long vehId);


	@Modifying
	@Transactional
	int deleteByApplicationNoAndVehicleId(Long appNo, Long vehId);

	@Modifying
	@Transactional
	@Query(value = "UPDATE MOTOR_DATA_DETAIL SET INCEPTION_DATE=to_date(?1,'DD/MM/YYYY'),EXPIRY_DATE=to_date(?2,'DD/MM/YYYY'), POLICYTYPE=?3,CURRENCY_TYPE=?4,QUOTE_NO=?5 WHERE APPLICATION_NO=?6 AND PRODUCT_ID=?7",nativeQuery=true)
	int updatePolicyDetailsByApplicationNo(String policyStartDate, String policyEndDate, Long policyType,
			String currencyType, Long quoteNo,Long appNo,Long productId);
	
	@Query(value = "SELECT deduct_id, deduct_end FROM motor_deductible_master mfb WHERE BRANCH_CODE=?1 AND ?2 BETWEEN SEATING_START AND SEATING_END AND TYPE_OF_BODY_ID IN(SELECT TYPE_OF_BODY_ID FROM MOTOR_BODYTYPE_DETAIL WHERE VTYPE_ID=?3 AND BODY_ID=?4) AND TRUNC(EFFECTIVE_DATE) <= TRUNC(SYSDATE) AND TYPE_OF_BODY_ID||DEDUCT_ID||AMEND_ID IN(SELECT MAX(TYPE_OF_BODY_ID||DEDUCT_ID||AMEND_ID) FROM (SELECT DEDUCT_ID,DEDUCT_END,TYPE_OF_BODY_ID,AMEND_ID FROM MOTOR_DEDUCTIBLE_MASTER MFB WHERE BRANCH_CODE=?1 AND ?2 BETWEEN MFB.SEATING_START AND MFB.SEATING_END AND MFB.TYPE_OF_BODY_ID IN (SELECT TYPE_OF_BODY_ID FROM MOTOR_BODYTYPE_DETAIL WHERE VTYPE_ID=?3 AND BODY_ID=?4) AND DEDUCT_ID=?5 AND TRUNC(EFFECTIVE_DATE) <= TRUNC(SYSDATE)) GROUP BY type_of_body_id || deduct_id) ORDER BY DEDUCT_ID",nativeQuery=true)
	List<Map<String,Object>> getDeductibleList(Object branchCode,Object seatCap,Object vehiType,Object bodyId,Object deductId);
	
	@Modifying
	@Transactional
	@Query(value ="UPDATE MOTOR_DATA_DETAIL SET REFERRAL_REMARKS=DECODE(REFERRAL_REMARKS,'','Sum Insured Limit Referral',REFERRAL_REMARKS||'~Sum Insured Limit Referral') WHERE SUMINSURED_VALUE_LOCAL>(Select Nvl(Insurance_End_Limit,0) From Login_User_Details LUDS Where Login_Id=?1 And Product_Id=?2 AND AMEND_ID=(select max (AMEND_ID) FROM Login_User_Details LUD where LUD.Login_Id=LUDS.Login_Id and LUD.Product_Id=LUDS.Product_Id)) AND APPLICATION_NO=?3",nativeQuery=true)
	int updateMddReferal(String loginId,String productId,Long appNo);

	List<MotorDataDetail> findByQuoteNo(Long quoteNo);
	
	
	@Query(value="select USERNAME from LOGIN_MASTER where LOGIN_ID=?1",nativeQuery=true)
	String getUserName(String loginId);
	
	@Query(value="SELECT MDD.CERTIFICATE_NO CERTIFICATE_NO, HPM.POLICY_NO POLICY_NO,HPM.LOGIN_ID LOGIN_ID,HPM.BRANCH_CODE BRANCH_CODE, REGISTRATION_NO VECHICLE_REG_NO ,TO_CHAR(HPM.INCEPTION_DATE,'dd-MON-yyyy hh24:mi:ss') ISSUE_DATE ,(SELECT TO_CHAR(POLICYENDDATE,'dd-MON-yyyy')||' 23:59:00 ' FROM MOTOR_POLICY_DETAILS WHERE QUOTENO=MDD.QUOTE_NO) EXPIRY_DATE FROM HOME_POSITION_MASTER HPM, MOTOR_DATA_DETAIL MDD ,MOTOR_CONDITION_MASTER MCM WHERE HPM.QUOTE_NO=?1 AND MCM.POLICY_TYPE_ID=MDD.VEHICLE_TYPE AND CASE POLICY_TYPE_ID WHEN '1' THEN COREAPPCODE WHEN '2' THEN COREAPPCODE WHEN '3' THEN COREAPPCODE WHEN '4' THEN COREAPPCODE END= CASE POLICY_TYPE_ID WHEN '1' THEN '400105' WHEN '2' THEN '400108' WHEN '3' THEN '400112' WHEN '4' THEN '400105' END AND MDD.VEHICLE_ID=?2 AND MDD.QUOTE_NO=HPM.QUOTE_NO AND HPM.APPLICATION_NO=MDD.APPLICATION_NO AND HPM.AMEND_ID=(SELECT MAX(AMEND_ID) FROM HOME_POSITION_MASTER HOPM WHERE HOPM.APPLICATION_NO=HPM.APPLICATION_NO AND HOPM.QUOTE_NO=HPM.QUOTE_NO)",nativeQuery=true)
	List<Map<String,Object>> getCertificateDetails(String quoteNo,String vehicleId);

}
