/*
 * Java domain class for entity "MotorFinanceBankMaster" 
 * Created on 2023-01-10 ( Date ISO 2023-01-10 - Time 16:19:40 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2023-01-10 ( 16:19:40 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.Madison.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.Madison.entity.MotorFinanceBankMaster;
import com.maan.Madison.entity.MotorFinanceBankMasterId;
/**
 * <h2>MotorFinanceBankMasterRepository</h2>
 *
 * createdAt : 2023-01-10 - Time 16:19:40
 * <p>
 * Description: "MotorFinanceBankMaster" Repository
 */
 
 
 
public interface MotorFinanceBankMasterRepository  extends JpaRepository<MotorFinanceBankMaster,MotorFinanceBankMasterId > , JpaSpecificationExecutor<MotorFinanceBankMaster> {

	List<MotorFinanceBankMaster> findByStatusIgnoreCase(String status);

}
