/*
 * Java domain class for entity "MotorDataDetail" 
 * Created on 2023-01-10 ( Date ISO 2023-01-10 - Time 16:19:19 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2023-01-10 ( 16:19:19 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.Madison.repository;

import java.util.Date;
import java.util.List;
import java.util.Map;

import javax.transaction.Transactional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.maan.Madison.entity.MotorDataDetail;
import com.maan.Madison.entity.MotorDataDetailId;
/**
 * <h2>MotorDataDetailRepository</h2>
 *
 * createdAt : 2023-01-10 - Time 16:19:19
 * <p>
 * Description: "MotorDataDetail" Repository
 */
 
 
@Repository 
public interface MotorDataDetailRepository  extends JpaRepository<MotorDataDetail,MotorDataDetailId > , JpaSpecificationExecutor<MotorDataDetail> {

	@Query(value ="SELECT APPLICATION_NO.NEXTVAL FROM DUAL",nativeQuery = true)
	Long getApplicatonNo();
	
	@Query(value ="SELECT ONEOFF_QUOTE.NEXTVAL FROM DUAL",nativeQuery = true)
	Long getQuoteNo();
	
	@Query(value = "SELECT NVL (MAX (VEHICLE_ID), 0)+1 FROM MOTOR_DATA_DETAIL WHERE APPLICATION_NO=?1",nativeQuery=true)
	Long getVehicleId(Long applicationNo);

	List<MotorDataDetail> findByApplicationNo(Long applicationNo);

	List<MotorDataDetail> findByApplicationNoAndReferralRemarksIsNotNull(Long applicationNo);

	MotorDataDetail findByApplicationNoAndVehicleId(Long appNo, Long vehId);


	int deleteByApplicationNoAndVehicleId(Long appNo, Long vehId);

	@Modifying
	@Transactional
	@Query(value = "UPDATE MOTOR_DATA_DETAIL SET INCEPTION_DATE=?1,EXPIRY_DATE=?2, POLICYTYPE=?3,CURRENCY_TYPE=?4,QUOTE_NO=?5 WHERE APPLICATION_NO=?6 AND PRODUCT_ID=?7",nativeQuery=true)
	int updatePolicyDetailsByApplicationNo(Date policyStartDate, Date policyEndDate, Long policyType,
			String currencyType, Long quoteNo,Long appNo,Long productId);
	
	@Query(value = "SELECT deduct_id, deduct_end FROM motor_deductible_master mfb WHERE BRANCH_CODE=?1 AND ?2 BETWEEN SEATING_START AND SEATING_END AND TYPE_OF_BODY_ID IN(SELECT TYPE_OF_BODY_ID FROM MOTOR_BODYTYPE_DETAIL WHERE VTYPE_ID=?3 AND BODY_ID=?4) AND TRUNC(EFFECTIVE_DATE) <= TRUNC(SYSDATE) AND TYPE_OF_BODY_ID||DEDUCT_ID||AMEND_ID IN(SELECT MAX(TYPE_OF_BODY_ID||DEDUCT_ID||AMEND_ID) FROM (SELECT DEDUCT_ID,DEDUCT_END,TYPE_OF_BODY_ID,AMEND_ID FROM MOTOR_DEDUCTIBLE_MASTER MFB WHERE BRANCH_CODE=?1 AND ?2 BETWEEN MFB.SEATING_START AND MFB.SEATING_END AND MFB.TYPE_OF_BODY_ID IN (SELECT TYPE_OF_BODY_ID FROM MOTOR_BODYTYPE_DETAIL WHERE VTYPE_ID=?3 AND BODY_ID=?4) AND DEDUCT_ID=?5 AND TRUNC(EFFECTIVE_DATE) <= TRUNC(SYSDATE)) GROUP BY type_of_body_id || deduct_id) ORDER BY DEDUCT_ID",nativeQuery=true)
	List<Map<String,Object>> getDeductibleList(Object branchCode,Object seatCap,Object vehiType,Object bodyId,Object deductId);
	
}
