/*
 * Java domain class for entity "MotorPolicyCoverData" 
 * Created on 2023-01-10 ( Date ISO 2023-01-10 - Time 16:20:08 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2023-01-10 ( 16:20:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.Madison.repository;

import java.util.List;
import java.util.Map;

import javax.transaction.Transactional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.maan.Madison.entity.MotorPolicyCoverData;
import com.maan.Madison.entity.MotorPolicyCoverDataId;

/**
 * <h2>MotorPolicyCoverDataRepository</h2>
 *
 * createdAt : 2023-01-10 - Time 16:20:08
 * <p>
 * Description: "MotorPolicyCoverData" Repository
 */
 
 
@Repository 
public interface MotorPolicyCoverDataRepository  extends JpaRepository<MotorPolicyCoverData,MotorPolicyCoverDataId > , JpaSpecificationExecutor<MotorPolicyCoverData> {


	List<MotorPolicyCoverData> findByApplicationNoOrderByDisplayOrderAsc(Long applicationNo);

	@Query(value = "SELECT DISTINCT Y_ID,DISPLAY_ORDER FROM MOTOR_POLICY_COVERAGE WHERE APPLICATION_NO=?1 AND BRANCH_CODE=?2 AND X_ID=?3 AND STATUS='Y' AND IS_SELECTED='Y' ORDER BY DISPLAY_ORDER ",nativeQuery=true)
	List<Map<String, Object>> getOpttionalCover(Long applicationNo, String branchCode, String policyType);

	@Modifying
	@Transactional
	@Query(value="UPDATE MOTOR_DATA_DETAIL SET POLICYTYPE=?1,OPTIONAL_COVER=?2 WHERE APPLICATION_NO=?3 AND AMEND_ID IN(SELECT MAX(AMEND_ID) FROM MOTOR_DATA_DETAIL WHERE APPLICATION_NO=?3)",nativeQuery=true)
	int updateOptionalCover(Object policyType,Object optionCov,Object appNo);
}
