/*
 * Java domain class for entity "MotorMakeMaster" 
 * Created on 2023-01-10 ( Date ISO 2023-01-10 - Time 16:19:46 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2023-01-10 ( 16:19:46 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.Madison.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;

import com.maan.Madison.entity.MotorMakeMaster;
import com.maan.Madison.entity.MotorMakeMasterId;
/**
 * <h2>MotorMakeMasterRepository</h2>
 *
 * createdAt : 2023-01-10 - Time 16:19:46
 * <p>
 * Description: "MotorMakeMaster" Repository
 */
 
 
 
public interface MotorMakeMasterRepository  extends JpaRepository<MotorMakeMaster,MotorMakeMasterId > , JpaSpecificationExecutor<MotorMakeMaster> {


	List<MotorMakeMaster> findByStatusOrderByMakeName(String status);
	
	@Query(value="select make_name from motor_make_master where make_Id =?1",nativeQuery=true)
	String getMakeNameById(String makeId);
	
	@Query(value="select model_name from motor_model_master where make_Id =?1 and model_id=?2",nativeQuery=true)
	String getModelNameById(String makeId,String modelId);
	
	@Query(value="select body_name from motor_bodytype_master where body_id =?1",nativeQuery=true)
	String getBodyNameById(String bodyId);
	
	@Query(value="select VEHICLETYPE_DESC from MOTOR_VEHICLETYPE_MASTER where VTYPE_ID=?1",nativeQuery=true)
	String getVehicleUsage(String vehUsage);
	
	
	

}
