/*
 * Java domain class for entity "MotorModelMaster" 
 * Created on 2023-01-10 ( Date ISO 2023-01-10 - Time 16:19:52 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2023-01-10 ( 16:19:52 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.Madison.repository;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.Madison.entity.MotorModelMaster;
import com.maan.Madison.entity.MotorModelMasterId;
/**
 * <h2>MotorModelMasterRepository</h2>
 *
 * createdAt : 2023-01-10 - Time 16:19:52
 * <p>
 * Description: "MotorModelMaster" Repository
 */
 
 
 
public interface MotorModelMasterRepository  extends JpaRepository<MotorModelMaster,MotorModelMasterId > , JpaSpecificationExecutor<MotorModelMaster> {


	List<MotorModelMaster> findByMakeIdAndStatusOrderByModelName(BigDecimal bigDecimal, String status);

}
