/*
 * Java domain class for entity "PersonalInfo" 
 * Created on 2023-01-10 ( Date ISO 2023-01-10 - Time 16:22:03 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2023-01-10 ( 16:22:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.Madison.repository;

import java.util.List;
import java.util.Map;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.maan.Madison.entity.PersonalInfo;
/**
 * <h2>PersonalInfoRepository</h2>
 *
 * createdAt : 2023-01-10 - Time 16:22:03
 * <p>
 * Description: "PersonalInfo" Repository
 */
 
 
@Repository 
public interface PersonalInfoRepository  extends JpaRepository<PersonalInfo,Long > , JpaSpecificationExecutor<PersonalInfo> {

	
	@Query(value="SELECT CUSTOMER_NUMBER_SEQ.NEXTVAL FROM DUAL",nativeQuery=true)
	Long getCustomerId();
	
	@Query(value="SELECT AGENCY_CODE FROM LOGIN_MASTER WHERE UPPER(USERTYPE)='BROKER' AND OA_CODE IN (SELECT OA_CODE FROM LOGIN_MASTER WHERE LOGIN_ID=?1)",nativeQuery=true)
	String getBrokerCode(String loginid);

	
	List<PersonalInfo> findByLoginIdAndCustomerTypeIgnoreCaseOrderByEntryDateDesc(String brokerCode, String customerType);

	@Query(value ="SELECT AGENCY_CODE,OA_CODE FROM LOGIN_MASTER WHERE LOGIN_ID=?1",nativeQuery=true)
	Map<String,Object> getAgencyCodeAndOaCode(String loginid);

	List<PersonalInfo> findByAgencyCodeAndCustomerTypeIgnoreCaseOrderByEntryDateDesc(String brokerCode,
			String customerType);
}
